# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 562)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 511, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.startDate = QtWidgets.QCalendarWidget(parent=self.gridLayoutWidget)
        self.startDate.setMaximumSize(QtCore.QSize(16777215, 200))
        self.startDate.setFirstDayOfWeek(QtCore.Qt.DayOfWeek.Monday)
        self.startDate.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.startDate.setObjectName("startDate")
        self.gridLayout.addWidget(self.startDate, 1, 1, 1, 1)
        self.endDate = QtWidgets.QDateEdit(parent=self.gridLayoutWidget)
        self.endDate.setCalendarPopup(True)
        self.endDate.setObjectName("endDate")
        self.gridLayout.addWidget(self.endDate, 2, 1, 1, 1)
        self.classBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.classBox.setObjectName("classBox")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.gridLayout.addWidget(self.classBox, 3, 1, 1, 1)
        self.calculateButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.calculateButton.setObjectName("calculateButton")
        self.gridLayout.addWidget(self.calculateButton, 4, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-weight: bold;\n"
"font-size: 20px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Koniec wypożyczenia"))
        self.label_4.setText(_translate("Dialog", "Klasa samochodu"))
        self.label_2.setText(_translate("Dialog", "Początek wypożyczenia"))
        self.endDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.classBox.setItemText(0, _translate("Dialog", "miejski"))
        self.classBox.setItemText(1, _translate("Dialog", "kompaktowy"))
        self.classBox.setItemText(2, _translate("Dialog", "van"))
        self.classBox.setItemText(3, _translate("Dialog", "suv"))
        self.calculateButton.setText(_translate("Dialog", "Oblicz koszt najmu"))
        self.label.setText(_translate("Dialog", "Wynajmij samochód"))
